- name: Check if the instance output exists
  stat:
    path:  '../outputs/{{ item.instance_name }}_managed_instance.json'
  register: instance_output

- name: Create managed instance configuration
  set_fact:
    managed_instance_configuration: '{{ lookup("template", item.template) }}'
  vars:
    subnet_id: '{{ item.subnet_id }}'
  when: instance_output.stat.exists == False

- name: Create the managed instance through the Spot API
  import_role:
    name: run_spotinst_instance
  vars:
    output_file_path: '../outputs/{{ item.instance_name }}_managed_instance.json'
  when: instance_output.stat.exists == False