- name: Check that the file exists
  stat:
    path: '{{ item.path }}'
  register: stat_result

- name: Create the file
  template:
    src: '{{ item.template }}'
    dest: '{{ item.path }}'
  when: not stat_result.stat.exists
