- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../vars.yml
  vars:
    state: absent
  name: Destroy
  tasks:
    - include_tasks: 
        file: ./tasks/spot_instance_down.yml
        apply:
          tags:
            ['servers']
      loop:
        - operator
        - w1
        - w2
        - w3
        - m1
        - m2
        - m3
      tags:
        ['servers']

    - import_role:
        name: run_vpc
      vars:
        output_file_path: '../outputs/vpc_stack.json'
        stack_name: '{{ project_name }}-vpc'
      tags: ['vpc']