- name: Create the CloudFormation stack
  cloudformation:
    stack_name: '{{ stack_name }}'
    state: 'present'
    region: '{{ aws_region }}'
    disable_rollback: true
    template_body: '{{ lookup("file", "cloudformation.yml") }}'
    template_parameters:
      ProjectName: '{{ project_name }}'
      VPCCidrBlock: '{{ cidr_block }}'
      PublicSubnetACidrBlock: '{{ public_subnet_a_cidr_block }}'
      PublicSubnetBCidrBlock: '{{ public_subnet_b_cidr_block }}'
      PublicSubnetCCidrBlock: '{{ public_subnet_c_cidr_block }}'
      AWSRegion: '{{ aws_region }}'
  register: output

- name: Save output
  copy:
    content: '{{ output | to_nice_json }}'
    dest: '{{ output_file_path }}'
